### ISSUE TITLE
filedrop Brocken ?

### ISSUE THREAD

**Issue by computerbastler** [Novik/ruTorrent#2268]
on the v4.0-beta.1

/rutorrent/plugins/filedrop//jquery.filedrop.js : 28] TypeError: jQuery.event.props is undefined
/rutorrent/ line 2 > injectedScript : 2459] TypeError: $(...).filedrop is not a function

cann fixed you

**Comment by Whisper40** [comment]
Maybe that too : JS error: [https://xxx/js/webui.js : 611] Uncaught TypeError: Cannot set properties of undefined (setting 'webui.lang')

**Comment by stickz** [comment]
@computerbastler This is a duplicate of #2257. Please clear your web browser cache when upgrading to ruTorrent to v4.0.

@Whisper40 You must upgrade your whole ruTorrent installation for v4.0 beta. Line 611 is a blank line, so you clearly didn't upgrade properly. You can not pick and choose which files you upgrade. There is API breakage with this version.

**Comment by computerbastler** [comment]
Have Clean Install

**Comment by stickz** [comment]
> Have Clean Install 😅 teste on my Phone Browser woking 🤣

This is excellent news! Thanks for testing the 4.0 beta package. I'm going to go ahead and close this since it's a duplicate. If you have any other problems with the beta package, please feel free to respond back here. And tag with me the @ symbol.
